import "@rundeck/ui-trellis/theme/scss/app.scss"
import "@rundeck/ui-trellis/theme/images/logos/rundeck-by-pd.svg"
import "@rundeck/ui-trellis/theme/images/logos/rundeck-combination.svg"
import "@rundeck/ui-trellis/theme/images/logos/oto-logo-blue.svg"
import "@rundeck/ui-trellis/theme/images/logos/oto-logo-green.svg"